version: "3.8"

services:
  backend:
    build: .
    image: mishel0702/connext
    container_name: connext
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - SPRING_PROFILES_ACTIVE
