services:
  backend:
    build: .
    image: connext-backend:latest
    container_name: connext
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - SPRING_PROFILES_ACTIVE
