services:
  backend:
    build: .
    container_name: connext
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - JPA_DDL_AUTO
      - JPA_SHOW_SQL